### PR TITLE
Qmb enhancements

### PR DESCRIPTION
**Pull request by jat255**
- qmb.fig and qmb.m updated to enable model shifting and rotating using push buttons
- also added zone axis control and viewing on main screen
- reorganized things a bit to fit more nicely, video below shows the gist of what's changed (sorry if you're on a slow connection!)

qmb-demo

### CODE REVIEW

**Comment by jat255** [comment]
Oh, and feel free to ignore changes to .gitignore. I couldn't figure out how to get those to not be included in the pull request.

**Comment by msarahan** [comment]
Looks good.  Would you mind squashing this into 1 commit, to keep the history cleaner?

Here's a guide I've used in the past:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by msarahan** [comment]
Nice improvement.  Thanks!

**Comment by jat255** [comment]
Ok, thanks for the link. I think I figured it out. First I rebased onto my fork, which didn't work, but then I rebased onto the upstream, and I think that solved it. Thanks for bearing with me as I figure out how to actually collaborate with git... Only used it for personal repos before!

**Comment by jat255** [comment]
Oh, that was quick. Glad I could help out!

**Comment by christophys** [comment]
You have indeed improved qmb quite a bit.  The video looks cool.  Thank you very much!!!!
-          Christoph.

**Pull request merged**
